
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zoli
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    
    private SQLCommands comm = new  SQLCommands();
    private DefaultListModel list;
    private DefaultListModel Shopping = new DefaultListModel();
    private ArrayList<Product> products = new ArrayList<Product>();
    
    public Customer() {
        initComponents();
        showProducts();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        ShoppingList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddToCartButton = new javax.swing.JButton();
        RemoveFromCartButton = new javax.swing.JButton();
        OrderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ProductList);

        jScrollPane2.setViewportView(ShoppingList);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Shopping cart");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Products");

        AddToCartButton.setText("AddToCart");
        AddToCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddToCartButtonMouseClicked(evt);
            }
        });

        RemoveFromCartButton.setText("RemoveFromCart");
        RemoveFromCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveFromCartButtonMouseClicked(evt);
            }
        });

        OrderButton.setText("Order");
        OrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(AddToCartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RemoveFromCartButton)
                .addGap(18, 18, 18)
                .addComponent(OrderButton)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddToCartButton)
                    .addComponent(RemoveFromCartButton)
                    .addComponent(OrderButton))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToCartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddToCartButtonMouseClicked
        try
        {
        int selected=0;
        float price;
        String name;
        selected = this.ProductList.getSelectedIndex();
        System.out.println(selected);
        String element = (String)this.list.get(selected);
        //Object elem = this.list.get(selected);
        System.out.println(element);
        String delims = "-";
        String[] tokens = element.split(delims);
        System.out.println(tokens[0]);
        name = tokens[0];
        comm.decrementProductFromWarehouse(tokens[0]);
        this.Shopping.addElement(element);
        delims = " ";
        System.out.println(tokens[1]);
        tokens = tokens[1].split(delims);
        System.out.println(tokens[1]);
        price = Float.parseFloat(tokens[1]);
        Product product = new Product(name,price);
        this.products.add(product);
        }
        catch(ArrayIndexOutOfBoundsException ex)
       {
           JOptionPane.showMessageDialog(null, "No product selected! Please select a product to remove!",
					  "Error", JOptionPane.ERROR_MESSAGE);
       }
        
       this.ShoppingList.setModel(this.Shopping);
       showProducts();
    }//GEN-LAST:event_AddToCartButtonMouseClicked

    private void RemoveFromCartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveFromCartButtonMouseClicked
        try
        {
        int selected=0;
        selected = this.ShoppingList.getSelectedIndex();
        System.out.println(selected);
        String element = (String)this.Shopping.get(selected);
        //Object elem = this.list.get(selected);
        System.out.println(element);
        String delims = "-";
        String[] tokens = element.split(delims);
        System.out.println(tokens[0]);
        comm.incrementProductFromWarehouse(tokens[0]);
        this.Shopping.removeElementAt(selected);
        this.products.remove(selected);
        }
        catch(ArrayIndexOutOfBoundsException ex)
       {
           JOptionPane.showMessageDialog(null, "No product selected! Please select a product to remove!",
					  "Error", JOptionPane.ERROR_MESSAGE);
       }
        
       this.ShoppingList.setModel(this.Shopping);
       showProducts();
    }//GEN-LAST:event_RemoveFromCartButtonMouseClicked

    private void OrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseClicked
        comm.orderProducts(this.products);
        this.products.clear();
        this.Shopping.removeAllElements();
        this.ShoppingList.setModel(this.Shopping);
        showProducts();
    }//GEN-LAST:event_OrderButtonMouseClicked

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }*/
   

    public void showProducts()
    {
        this.list = comm.getWarehouseContent();
        this.ProductList.setModel(this.list);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JButton OrderButton;
    private javax.swing.JList ProductList;
    private javax.swing.JButton RemoveFromCartButton;
    private javax.swing.JList ShoppingList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
